# Generated by Django 2.1.7 on 2019-02-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_barang_deskripsi_produk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_barang',
            name='deskripsi_produk',
            field=models.TextField(max_length=255),
        ),
    ]
