# Generated by Django 2.1.7 on 2019-02-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190214_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_barang',
            name='deskripsi_produk',
        ),
        migrations.AddField(
            model_name='home_barang',
            name='deksripsi',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
