# Generated by Django 2.1.7 on 2019-02-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_home_barang_deksripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_barang',
            name='deskripsi',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
